# Etapa 1: Construcción
FROM node:20 AS build
WORKDIR /app
COPY frontend-vue/package*.json ./
RUN npm install
COPY frontend-vue/ .
RUN npm run build

# Etapa 2: Servidor de producción
FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
# Copiaremos una configuración de nginx personalizada en el siguiente paso
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
