# Etapa 1: Construcción
FROM node:20 AS build
WORKDIR /app
COPY booking-frontend/package*.json ./
RUN npm install
COPY booking-frontend/ .
RUN npm run build

# Etapa 2: Servidor de producción
FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
# Copiaremos una configuración de nginx personalizada en el siguiente paso
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["/bin/sh", "-c", "envsubst '${API_GATEWAY_URL} ${API_GATEWAY_HOST}' < /etc/nginx/conf.d/default.conf > /etc/nginx/conf.d/default.conf.temp && mv /etc/nginx/conf.d/default.conf.temp /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"]
