services:
  - type: web
    name: alojamientos-api
    env: docker
    dockerContext: ./AlojamientoPrototipo
    dockerfilePath: ./AlojamientoPrototipo/Dockerfile.Alojamientos
    plan: free
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ConnectionStrings__ConexionAlojamientos
        value: Host=aws-1-us-west-1.pooler.supabase.com;Port=5432;Database=postgres;Username=postgres.tnxniynmtizuymfjyalr;Password=Supabase_2?;SSL Mode=Require;Trust Server Certificate=true

  - type: web
    name: facturacion-api
    env: docker
    dockerContext: ./AlojamientoPrototipo
    dockerfilePath: ./AlojamientoPrototipo/Dockerfile.Facturacion
    plan: free
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ConnectionStrings__ConexionFacturacion
        value: Host=aws-1-us-west-1.pooler.supabase.com;Port=5432;Database=postgres;Username=postgres.tnxniynmtizuymfjyalr;Password=Supabase_2?;SSL Mode=Require;Trust Server Certificate=true

  - type: web
    name: reservas-api
    env: docker
    dockerContext: ./AlojamientoPrototipo
    dockerfilePath: ./AlojamientoPrototipo/Dockerfile.Reservas
    plan: free
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ConnectionStrings__ConexionReservas
        value: Host=aws-1-us-west-1.pooler.supabase.com;Port=5432;Database=postgres;Username=postgres.tnxniynmtizuymfjyalr;Password=Supabase_2?;SSL Mode=Require;Trust Server Certificate=true
      - key: GrpcUrls__Alojamientos
        fromService:
          type: web
          name: alojamientos-api
          envVarKey: RENDER_EXTERNAL_URL

  - type: web
    name: usuarios-api
    env: docker
    dockerContext: ./AlojamientoPrototipo
    dockerfilePath: ./AlojamientoPrototipo/Dockerfile.Usuarios
    plan: free
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ConnectionStrings__ConexionUsuarios
        value: Host=aws-1-us-west-1.pooler.supabase.com;Port=5432;Database=postgres;Username=postgres.tnxniynmtizuymfjyalr;Password=Supabase_2?;SSL Mode=Require;Trust Server Certificate=true

  - type: web
    name: api-gateway
    env: docker
    dockerContext: ./AlojamientoPrototipo
    dockerfilePath: ./AlojamientoPrototipo/Dockerfile.ApiGateway
    plan: free
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ReverseProxy__Clusters__alojamientos-cluster__Destinations__destination1__Address
        fromService:
          type: web
          name: alojamientos-api
          envVarKey: RENDER_EXTERNAL_URL
      - key: ReverseProxy__Clusters__reservas-cluster__Destinations__destination1__Address
        fromService:
          type: web
          name: reservas-api
          envVarKey: RENDER_EXTERNAL_URL
      - key: ReverseProxy__Clusters__usuarios-cluster__Destinations__destination1__Address
        fromService:
          type: web
          name: usuarios-api
          envVarKey: RENDER_EXTERNAL_URL
      - key: ReverseProxy__Clusters__facturacion-cluster__Destinations__destination1__Address
        fromService:
          type: web
          name: facturacion-api
          envVarKey: RENDER_EXTERNAL_URL
      - key: Microservices__UsuariosUrl
        fromService:
          type: web
          name: usuarios-api
          envVarKey: RENDER_EXTERNAL_URL
      - key: Microservices__AlojamientosUrl
        fromService:
          type: web
          name: alojamientos-api
          envVarKey: RENDER_EXTERNAL_URL
      - key: Microservices__ReservasUrl
        fromService:
          type: web
          name: reservas-api
          envVarKey: RENDER_EXTERNAL_URL
      - key: Microservices__FacturacionUrl
        fromService:
          type: web
          name: facturacion-api
          envVarKey: RENDER_EXTERNAL_URL

  - type: web
    name: booking-frontend
    env: docker
    dockerContext: .
    dockerfilePath: ./Dockerfile.front
    plan: free
    envVars:
      - key: API_GATEWAY_URL
        fromService:
          type: web
          name: api-gateway
          envVarKey: RENDER_EXTERNAL_URL
      - key: API_GATEWAY_HOST
        fromService:
          type: web
          name: api-gateway
          envVarKey: RENDER_EXTERNAL_HOSTNAME
